### ISSUE TITLE
Unable to populate the summary

### ISSUE THREAD

**Issue by mandclu** [akilli/ck4#1]
I'm excited to use this plugin, but when I use the demo and create a details element, there doesn't seem to be a way to populate the summary, as every time I try to click in there it toggles the element instead of moving the cursor there. How can I enter text into the summary?

**Comment by akilli** [comment]
Hi mandclu,
just realized that there seems to be a regression with Chrome, whilst Firefox works fine. I'll have a look on that.

**Comment by akilli** [comment]
OK, problem appears in chrome if summary is empty which is now the default when inserting a new widget. I used a default text before.

**Comment by akilli** [comment]
Hi @mandclu 
please try again at https://akilli.github.io/rte/ck4/

**Comment by akilli** [comment]
You can download the new version 2.9 @ https://ckeditor.com/cke4/addon/detail
